### ISSUE TITLE
[Suggestion] Generate table names

### ISSUE THREAD

**Issue by gaetschwartz** [medz/prisma-dart#223]
It would be helpful if table names could be generates as well ! Something like 

```dart
enum PrismaTables {
	table1("table_1"),
	table2("table_2");

	final String databaseName;
	PrismaTables(this.databaseName);
}
```

**Comment by medz** [comment]
@gaetschwartz This seems to be a requirement request, we need to talk about the necessity of the use case.

In addition, if you need to make a program like CRUD, you may need to use it, and you can also generate table fields.

Another, is it necessary for us to disclose DMMF, because DMMF contains more database information.

**Comment by medz** [comment]
I understand, because I have similar needs, I added it to #216, the current available version I use https://pub.dev/packages/prisma_generator_helper to get DMMF, just write simple code, and then in `schema Add new generators to .prisma`.

But I'm taking your advice and adding dmmf to the default build in the next version.

**Comment by gaetschwartz** [comment]
Thanks, I'll look into that ! Could you elaborate ? I'm not sure to understand your instructions ?

**Comment by medz** [comment]
`OnGenerate 'will pass in an instance of' GeneratorOptions' as a parameter, which contains DMMF. You only need to call the 'toJson' method to convert it into a JSON object. You can create a file that contains DMMF content.

**Comment by medz** [comment]
@gaetschwartz Already supported in v4 version
