### ISSUE TITLE
Not compatible with Prisma v5.x

### ISSUE THREAD

**Issue by SBNTT** [medz/prisma-dart#249]
Latest major version of Prisma is not compatible. Documentation simply mention to run `npm i prisma` which is not correct anymore.

`npm i prisma@^4.16.2` is the right one :)

**Comment by medz** [comment]
Sorry, I know about the problem. Because my personal work is too busy, I have to work almost ten hours a day.
I can't find time to adapt to the new Prisma 5, I think, this problem should be half a month before I have time to deal with it.

Of course, if it would be nice to see you create a PR to adapt the Prisma JSON protocol.

Alternatively, contact me via Discord to resolve this issue as a paid service, then discuss remuneration on Discord.

**Comment by deadblit** [comment]
My schema wasn't working, it could not generate correctly the client. Downgrading prisma to `4.16.2` made both `npx prisma generate` and `build_runner` work for me.

**Comment by medz** [comment]
I'm actively developing a new version to adapt to Prisma 5

**Comment by medz** [comment]
Brought new progress news, v4 version is about to fix it! Please follow #289 #290

Also, I think I need to establish a more comprehensive testing coverage to prevent this type of problem from occurring in the future.

**Comment by medz** [comment]
in `3.x` fixed
