### ISSUE TITLE
Error when using "npx prisma generate" to create the "generated_dart_client" folder

### ISSUE THREAD

**Issue by iamhaghigh1** [medz/prisma-dart#407]
When I run the command npx prisma generate , I encounter errors.

.env file
![image](https://github.com/medz/prisma-dart/assets/174028426/48f24bf5-769e-45e5-8cf9-769ad41e1ab0)

schema.prisma
![image](https://github.com/medz/prisma-dart/assets/174028426/cdf81dc0-3ce7-437a-bfaa-350a1d2998b7)

npx prism generate
![image](https://github.com/medz/prisma-dart/assets/174028426/74ff3ea2-df8a-436e-9cf7-2e0e8a4ca1cd)

after the generate
![image](https://github.com/medz/prisma-dart/assets/174028426/037be596-1c69-4bc3-abcb-c6f4557fab2c)

what shoul i do?

**Comment by medz** [comment]
@iamhaghigh1 So what is the error? Your screenshot shows that the file reports an error. But you need to expose the specific error.

**Comment by medz** [comment]
In addition, I noticed that you are using version 4.1. Can you use version 5.0?

Because this project is currently maintained by me alone, and there is no collaborator. So I don't have time to maintain the previous major version.

Therefore, the current maintenance strategy is to only maintain the current major version, and all bugs are fixed in the current major version.

**Comment by iamhaghigh1** [comment]
In the training course, he said to use version 4.16.2, because the higher version has problems.
I tried both version 4.16.2 and the latest version, but it still has a problem.

I use the latest version.
![image](https://github.com/medz/prisma-dart/assets/174028426/58d4ae60-12db-466c-84b3-e373340d331f)

there are too many errors
![image](https://github.com/medz/prisma-dart/assets/174028426/8cbe87c9-7447-4dcb-b784-b2c125de9ec6)
![image](https://github.com/medz/prisma-dart/assets/174028426/ee0b2d30-90f7-47c0-a00a-2770b32e002c)
![image](https://github.com/medz/prisma-dart/assets/174028426/60690078-44c2-44ed-bb17-56e4178ab2c0)
![image](https://github.com/medz/prisma-dart/assets/174028426/0d258998-0ba9-4056-9d61-ae798efc3b3a)
![image](https://github.com/medz/prisma-dart/assets/174028426/5a8d911d-22ca-473a-8a1a-0b54c18e8733)
![image](https://github.com/medz/prisma-dart/assets/174028426/0aa0ec6a-68d5-4d7b-9ca3-8d5eb32f8c2b)
![image](https://github.com/medz/prisma-dart/assets/174028426/5d70bc68-8b45-4e3c-bc9e-5737c20dcc7e)

**Comment by medz** [comment]
@iamhaghigh1 The training course was probably written in the 4.x era, when Prisma made breaking changes that caused some unforeseen problems.

But they were fixed in subsequent versions. I recommend you use `orm: ^5.0.4` and the latest version of Prisma CLI (`5.16`).

In addition, I noticed that you might be using a more stringent custom lint rule. The `orm` package only satisfies `package:lints/recommended.yaml`, so you need to exclude the generated files from your custom lint rules. If you use the `package:lints/recommended.yaml` rule, no processing is required.

**Comment by medz** [comment]
You can find the examples we provide at https://github.com/medz/prisma-dart/tree/main/examples, but we do not use more stringent third-party custom lint rules.

**Comment by medz** [comment]
- #325
