### ISSUE TITLE
StringFilter miss the IN operator

### ISSUE THREAD

**Issue by AndryHTC** [medz/prisma-dart#428]
![Immagine WhatsApp 2024-09-18 ore 09 28 08_d8da15d9](https://github.com/user-attachments/assets/c6983b38-ee40-40e7-a909-70e5c09b3cc7)

**Comment by medz** [comment]
@AndryHTC Can you tell me the type of database you are using

**Comment by AndryHTC** [comment]
> @AndryHTC Can you tell me the type of database you are using

Postgres

**Comment by medz** [comment]
Hay @AndryHTC: Unfortunately, I can't reproduce the problem you are having. So I created an example using postgres, located at 👉 examples/with_postgres

<img width="754" alt="image" src="https://github.com/user-attachments/assets/4db1811f-4ace-4965-b8f2-783a6680dc7a">
<img width="760" alt="image" src="https://github.com/user-attachments/assets/1b6f5418-e9ad-4b3d-95a3-1445cd1800be">

I have everything working fine here, with `in` string filtering.

PS: Since `in` is a Dart reserved keyword, it has been renamed to `$in`.

**Comment by medz** [comment]
@AndryHTC Has there been any progress?

**Comment by AndryHTC** [comment]
I found the problem, which may be related to IntelliJ autocompletion, as in VS Code I can see the `$in`.

Thank you
